name: examen-workflow

on: 
    push:
        branches:
            - nueva-caracteristica 

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
          - name: Bajar codigo
            uses: actions/checkout@v4
  
          - name: Instalar librerias
            run: |
                python -m pip install --upgrade pip
                pip install pytest 
              
          - name: Ejecutar test
            run: pytest test.py
  
          - name: Build
            uses: docker/build-push-action@v5
